CREATE TABLE personnes (
    id SERIAL PRIMARY KEY,
    nom VARCHAR(50),
    age INT,
    ville VARCHAR(50)
);

INSERT INTO personnes (nom, age, ville) VALUES
('Alice', 30, 'Paris'),
('Bob', 25, 'Lyon'),
('Charlie', 35, 'Marseille'),
('Diana', 28, 'Toulouse'),
('Erik', 45, 'Nice'),
('Fanny', 32, 'Nantes'),
('George', 38, 'Strasbourg'),
('Helena', 29, 'Bordeaux'),
('Ivan', 22, 'Lille'),
('Julie', 27, 'Rennes'),
('Karl', 34, 'Reims'),
('Laura', 42, 'Saint-Étienne'),
('Mohamed', 31, 'Toulon'),
('Nora', 21, 'Le Havre'),
('Oscar', 40, 'Grenoble'),
('Patricia', 26, 'Dijon'),
('Quentin', 30, 'Angers'),
('Rita', 24, 'Villeurbanne'),
('Steve', 50, 'Montpellier'),
('Tina', 49, 'Brest'),
('Ulysse', 20, 'Nîmes'),
('Valerie', 36, 'Clermont-Ferrand'),
('William', 55, 'Saint-Denis'),
('Xavier', 60, 'La Rochelle'),
('Yasmine', 23, 'Le Mans'),
('Zoé', 33, 'Aix-en-Provence'),
('André', 41, 'Amiens'),
('Brigitte', 37, 'Limoges'),
('Cyril', 19, 'Annecy'),
('Danielle', 43, 'Perpignan'),
('Emmanuel', 29, 'Boulogne-Billancourt'),
('Flore', 36, 'Mulhouse'),
('Gaspard', 28, 'Caen'),
('Hugo', 47, 'Rouen'),
('Ines', 22, 'Nancy'),
('Jocelyn', 53, 'Argenteuil'),
('Karim', 39, 'Montreuil'),
('Léa', 25, 'Tours'),
('Marc', 54, 'Versailles'),
('Nina', 24, 'Colombes'),
('Olivier', 31, 'Asnières-sur-Seine'),
('Paula', 27, 'Rueil-Malmaison'),
('Rémi', 35, 'Pau'),
('Sonia', 46, 'Aubervilliers'),
('Théo', 17, 'Poitiers'),
('Umberto', 58, 'Metz'),
('Viviane', 63, 'Besançon'),
('Willy', 29, 'Orléans'),
('Xenia', 41, 'Saint-Paul'),
('Yan', 32, 'Antibes'),
('Zelda', 37, 'Cannes'),
-- 
('Aaron', 22, 'Avignon'),
('Adele', 33, 'Bourges'),
('Adrien', 44, 'Calais'),
('Agnes', 26, 'Dunkerque'),
('Alain', 30, 'Evry'),
('Albert', 31, 'Fontainebleau'),
('Alfred', 29, 'Grasse'),
('Alice', 34, 'Hyères'),
('Aline', 35, 'Issy-les-Moulineaux'),
('Amandine', 23, 'Laval'),
('Amelie', 28, 'Levallois-Perret'),
('Anais', 32, 'Mâcon'),
('Anatole', 45, 'Neuilly-sur-Seine'),
('Andre', 27, 'Pantin'),
('Angele', 38, 'Quimper'),
('Anita', 41, 'Rodez'),
('Anna', 22, 'Saint-Brieuc'),
('Annick', 33, 'Sète'),
('Antoine', 29, 'Troyes'),
('Ariane', 40, 'Uzès'),
('Armand', 24, 'Vichy'),
('Armel', 35, 'Wattrelos'),
('Arthur', 28, 'Yerres'),
('Astrid', 39, 'Zephyrine'),
('Aurelie', 20, 'Aurillac'),
('Aurore', 21, 'Bayonne'),
('Axel', 28, 'Brive-la-Gaillarde'),
('Baptiste', 26, 'Chalon-sur-Saône'),
('Beatrice', 34, 'Dieppe'),
('Benjamin', 33, 'Epernay'),
('Bernard', 37, 'Franconville'),
('Bertrand', 30, 'Givors'),
('Blaise', 41, 'Houilles'),
('Blandine', 29, 'Ivry-sur-Seine'),
('Brice', 33, 'Joinville-le-Pont'),
('Bruno', 36, 'Kremlin-Bicêtre'),
('Camille', 22, 'La Ciotat'),
('Candice', 35, 'Laon'),
('Carine', 28, 'Mantes-la-Jolie'),
('Carole', 40, 'Narbonne'),
('Catherine', 31, 'Olivet'),
('Cedric', 27, 'Périgueux'),
('Celia', 29, 'Quincy'),
('Chantal', 42, 'Rambouillet'),
('Charles', 19, 'Sannois'),
('Charlotte', 37, 'Thionville'),
('Chloe', 25, 'Vannes');